import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-cold-storage-invoice-capacity-audit",
  "engine": "recovery",
  "title": "Cold Storage Invoice & Capacity Audit",
  "shortTitle": "Cold Storage Invoice and Capacity Audit",
  "tagline": "Recalculate pallet-day storage, handling, temperature services, and capacity commitments across cold facilities.",
  "industry": "Cold Chain Cost Recovery",
  "buyer": "Food, pharmaceutical, and cold-chain operators",
  "uiPort": 4700,
  "apiPort": 5700,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Cold Storage Invoice & Capacity Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits in one accountable workflow. Recalculate pallet-day storage, handling, temperature services, and capacity commitments across cold facilities.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Cold Storage Invoice & Capacity Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("storage-agreement-library","CSI01","Storage agreement library","Execute storage agreement library using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed storage agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Storage agreement library Reference","text","CSI01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("facility-zone-registry","CSI02","Facility zone registry","Execute facility zone registry using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed facility zone registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Facility zone registry Reference","text","CSI02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("lot-pallet-ingestion","CSI03","Lot pallet ingestion","Execute lot pallet ingestion using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed lot pallet ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Lot pallet ingestion Reference","text","CSI03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("daily-inventory-reconstruction","CSI04","Daily inventory reconstruction","Execute daily inventory reconstruction using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed daily inventory reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Daily inventory reconstruction Reference","text","CSI04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("pallet-day-calculation","CSI05","Pallet-day calculation","Execute pallet-day calculation using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed pallet-day calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Pallet-day calculation Reference","text","CSI05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("minimum-capacity-validation","CSI06","Minimum capacity validation","Execute minimum capacity validation using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed minimum capacity validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Minimum capacity validation Reference","text","CSI06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("blast-freezing-charge","CSI07","Blast freezing charge","Execute blast freezing charge using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed blast freezing charge decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Blast freezing charge Reference","text","CSI07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("inbound-handling-audit","CSI08","Inbound handling audit","Execute inbound handling audit using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed inbound handling audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Inbound handling audit Reference","text","CSI08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("outbound-handling-audit","CSI09","Outbound handling audit","Execute outbound handling audit using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed outbound handling audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Outbound handling audit Reference","text","CSI09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("temperature-excursion-credit","CSI10","Temperature excursion credit","Execute temperature excursion credit using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed temperature excursion credit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Temperature excursion credit Reference","text","CSI10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("energy-surcharge-validation","CSI11","Energy surcharge validation","Execute energy surcharge validation using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed energy surcharge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Energy surcharge validation Reference","text","CSI11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("invoice-recalculation","CSI12","Invoice recalculation","Execute invoice recalculation using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Invoice recalculation Reference","text","CSI12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("facility-dispute-workflow","CSI13","Facility dispute workflow","Execute facility dispute workflow using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed facility dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Facility dispute workflow Reference","text","CSI13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("credit-reconciliation","CSI14","Credit reconciliation","Execute credit reconciliation using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Credit reconciliation Reference","text","CSI14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]}),
feature("facility-product-analytics","CSI15","Facility product analytics","Execute facility product analytics using storage agreements, pallets, lots, temperatures, receipts, shipments, daily inventories, blast freezing, handling, energy surcharges, invoices, and credits.","Produce a governed facility product analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Facility / Storage Account","text","Facility / Storage Account · Standard Case"],["caseReference","Facility product analytics Reference","text","CSI15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1291250],["supportedAmount","Evidence-Supported Amount","currency",1084650],["domainDriver","Service Type","select","Frozen storage",["Frozen storage","Chilled storage","Blast freezing"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Storage agreement library case","Facility zone registry case","Lot pallet ingestion case","Daily inventory reconstruction case","Pallet-day calculation case"]})
]);
